In [1]:
import sys
from pathlib import Path
# Add project root to Python path
sys.path.append(str(Path().resolve().parent))

In [2]:
from app.catalog.loader import load_catalog

In [5]:
catalog = load_catalog()
type(catalog)

list

In [6]:
len(catalog)

377

In [7]:
catalog[0]

{'entity_id': '4302',
 'name': 'Global Skills Development Report',
 'link': 'https://www.shl.com/products/product-catalog/view/global-skills-development-report/',
 'scraped_at': '2026-05-08T10:40:21.464836+00:00',
 'job_levels': ['Director',
  'Entry-Level',
  'Executive',
  'General Population',
  'Graduate',
  'Manager',
  'Mid-Professional',
  'Front Line Manager',
  'Supervisor'],
 'job_levels_raw': 'Director, Entry-Level, Executive, General Population, Graduate, Manager, Mid-Professional, Front Line Manager, Supervisor,',
 'languages': [],
 'languages_raw': '',
 'duration': '',
 'duration_raw': '',
 'status': 'ok',
 'remote': 'yes',
 'adaptive': 'no',
 'description': 'This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.',
 'keys': ['Ability & Aptitude',
  'Assessment Exercises',
  'Biodata & Situational Judgment',
  'Competencies',
  'Development & 360',
  'Personality & Behavior']}

In [8]:
from pprint import pprint

pprint(catalog[0])

{'adaptive': 'no',
 'description': 'This report is designed to be given to individuals who have '
                'completed the Global Skills Assessment (GSA). With coverage '
                'across the Great 8 Domains, this measure of self-reported '
                'behaviors offers a complete overview of their current skills. '
                'Participants receive actionable tips on leveraging their top '
                'skill strengths and how they might develop their growth '
                'skills.',
 'duration': '',
 'duration_raw': '',
 'entity_id': '4302',
 'job_levels': ['Director',
                'Entry-Level',
                'Executive',
                'General Population',
                'Graduate',
                'Manager',
                'Mid-Professional',
                'Front Line Manager',
                'Supervisor'],
 'job_levels_raw': 'Director, Entry-Level, Executive, General Population, '
                   'Graduate, Manager, Mid-Professional, Front Line Manager, '
                   'Supervisor,',
 'keys': ['Ability & Aptitude',
          'Assessment Exercises',
          'Biodata & Situational Judgment',
          'Competencies',
          'Development & 360',
          'Personality & Behavior'],
 'languages': [],
 'languages_raw': '',
 'link': 'https://www.shl.com/products/product-catalog/view/global-skills-development-report/',
 'name': 'Global Skills Development Report',
 'remote': 'yes',
 'scraped_at': '2026-05-08T10:40:21.464836+00:00',
 'status': 'ok'}

In [9]:
import pandas as pd
df = pd.DataFrame(catalog)

In [10]:
df.head()

,entity_id,name,link,scraped_at,job_levels,job_levels_raw,languages,languages_raw,duration,duration_raw,status,remote,adaptive,description,keys
0,4302,Global Skills Development Report,https://www.shl.com/products/product-catalog/v...,2026-05-08T10:40:21.464836+00:00,"[Director, Entry-Level, Executive, General Pop...","Director, Entry-Level, Executive, General Popu...",[],,,,ok,yes,no,This report is designed to be given to individ...,"[Ability & Aptitude, Assessment Exercises, Bio..."
1,3827,.NET Framework 4.5,https://www.shl.com/products/product-catalog/v...,2026-05-08T10:39:46.810448+00:00,"[Professional Individual Contributor, Mid-Prof...","Professional Individual Contributor, Mid-Profe...",[English (USA)],"English (USA),",30 minutes,Approximate Completion Time in minutes = 30,ok,yes,yes,The.NET Framework 4.5 test measures knowledge ...,[Knowledge & Skills]
2,4094,.NET MVC (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:39:53.276083+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",17 minutes,Approximate Completion Time in minutes = 17,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]
3,4099,.NET MVVM (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:41:53.047159+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",5 minutes,Approximate Completion Time in minutes = 5,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]
4,4018,.NET WCF (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:41:58.935422+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",11 minutes,Approximate Completion Time in minutes = 11,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   entity_id       377 non-null    str
 1   name            377 non-null    str
 2   link            377 non-null    str
 3   scraped_at      377 non-null    str
 4   job_levels      377 non-null    object
 5   job_levels_raw  377 non-null    str
 6   languages       377 non-null    object
 7   languages_raw   377 non-null    str
 8   duration        377 non-null    str
 9   duration_raw    377 non-null    str
 10  status          377 non-null    str
 11  remote          377 non-null    str
 12  adaptive        377 non-null    str
 13  description     377 non-null    str
 14  keys            377 non-null    object
dtypes: object(3), str(12)
memory usage: 44.3+ KB

In [12]:
df.columns.tolist()

['entity_id',
 'name',
 'link',
 'scraped_at',
 'job_levels',
 'job_levels_raw',
 'languages',
 'languages_raw',
 'duration',
 'duration_raw',
 'status',
 'remote',
 'adaptive',
 'description',
 'keys']

In [13]:
df.shape

(377, 15)

In [14]:
df.isna().sum()

entity_id         0
name              0
link              0
scraped_at        0
job_levels        0
job_levels_raw    0
languages         0
languages_raw     0
duration          0
duration_raw      0
status            0
remote            0
adaptive          0
description       0
keys              0
dtype: int64

In [17]:
from app.catalog.preprocess import build_search_document

In [19]:
search_doc = build_search_document(catalog[0])
print(search_doc)

Name: Global Skills Development Report
Description: This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.
Assessment Type: Ability & Aptitude, Assessment Exercises, Biodata & Situational Judgment, Competencies, Development & 360, Personality & Behavior
Job Levels: Director, Entry-Level, Executive, General Population, Graduate, Manager, Mid-Professional, Front Line Manager, Supervisor
Languages:
Duration:
Adaptive: no
Remote: yes

In [20]:
df["search_document"] = [
    build_search_document(a)
    for a in catalog
]

In [21]:
df[["name", "search_document"]].head()

,name,search_document
0,Global Skills Development Report,Name: Global Skills Development Report\nDescri...
1,.NET Framework 4.5,Name: .NET Framework 4.5\nDescription: The.NET...
2,.NET MVC (New),Name: .NET MVC (New)\nDescription: Multi-choic...
3,.NET MVVM (New),Name: .NET MVVM (New)\nDescription: Multi-choi...
4,.NET WCF (New),Name: .NET WCF (New)\nDescription: Multi-choic...

In [22]:
from pathlib import Path
output_path = Path("../data/processed/catalog_processed.csv")
df.to_csv(output_path, index=False)

In [23]:
df["name"].str.contains("Report", case=False).sum()

np.int64(57)

In [24]:
df[df["name"].str.contains("Report", case=False)][["name", "keys"]].head(10)

,name,keys
0,Global Skills Development Report,"[Ability & Aptitude, Assessment Exercises, Bio..."
82,Digital Readiness Development Report - IC,[Personality & Behavior]
83,Digital Readiness Development Report - Manager,[Personality & Behavior]
87,DSI v1.1 Interpretation Report,[Personality & Behavior]
97,Enterprise Leadership Report 1.0,[Personality & Behavior]
98,Enterprise Leadership Report 2.0,[Personality & Behavior]
107,Executive Scenarios Narrative Report,[Biodata & Situational Judgment]
108,Executive Scenarios Profile Report,[Biodata & Situational Judgment]
128,Graduate Scenarios Narrative Report,[Biodata & Situational Judgment]
129,Graduate Scenarios Profile Report,[Biodata & Situational Judgment]

In [25]:
df["keys"].explode().value_counts()

keys
Knowledge & Skills                240
Personality & Behavior             67
Simulations                        43
Ability & Aptitude                 32
Competencies                       19
Biodata & Situational Judgment     17
Development & 360                   7
Assessment Exercises                2
Name: count, dtype: int64

In [26]:
df["job_levels"].explode().value_counts()

job_levels
Mid-Professional                       304
Professional Individual Contributor    296
Graduate                               140
Manager                                117
Entry-Level                            114
Front Line Manager                      75
Supervisor                              73
Director                                55
Executive                               55
General Population                      45
Name: count, dtype: int64